When bin/develop is called without arguments, show the help text.
This is instead of an ugly error:

```
$ bin/develop
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.1/bin/develop", line 15, in <module>
    sys.exit(mr.developer.develop.develop())
  File "/Users/maurits/shared-eggs/cp310/mr.developer-2.0.4-py3.10.egg/mr/developer/develop.py", line 103, in __call__
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```