[FIX] Mock's patch contextmanager now requires exc_info like arguments
Fixes

```
  File "/home/user/mr.developer/.tox/py38/lib/python3.8/site-packages/mock/mock.py", line 1545, in __exit__
    return exit_stack.__exit__(*exc_info)
  File "/usr/lib/python3.8/contextlib.py", line 483, in __exit__
    received_exc = exc_details[0] is not None
IndexError: tuple index out of rang
```

when running tests